version: "3.9"

services:
  frontend:
    build: ./frontend-angular
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env.docker

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3001
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      - GF_SECURITY_COOKIE_SECURE=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - prometheus



  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"


  promtail:
    image: grafana/promtail:2.9.8
    container_name: promtail
    environment:
      - DOCKER_API_VERSION=1.44
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./monitoring/promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - loki



